In [2]:
import torch
import matplotlib as plt
%matplotlib inline
print(torch.__version__)


2.1.2


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6]],
                       [[1, 2, 3], 
                       [6, 7, 8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [6, 7, 8]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([2, 2, 3])

In [41]:
for i in torch.arange(3): print(TENSOR[1][1][i].item())

6
7
8


In [42]:
# random tensors
random_tensors = torch.rand(3, 4)
random_tensors

tensor([[0.2602, 0.5477, 0.4537, 0.5726],
        [0.8285, 0.2595, 0.4941, 0.1279],
        [0.6371, 0.6251, 0.2142, 0.4787]])

In [43]:
random_tensors.ndim

2

In [52]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
# use torch.range()
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# creating tensors like (same shape as the input)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
float16_tensor = torch.tensor((2, 3, 4), dtype=torch.float16)
float16_tensor

tensor([2., 3., 4.], dtype=torch.float16)

In [71]:
float16_tensor + 8

tensor([10., 11., 12.], dtype=torch.float16)

In [72]:
# manipulating tensors

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [73]:
tensor * tensor

tensor([1, 4, 9])

In [74]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [82]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 614 µs, sys: 184 µs, total: 798 µs
Wall time: 698 µs


In [90]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 50 µs, sys: 15 µs, total: 65 µs
Wall time: 99.4 µs


tensor(14)

In [94]:
### can transpose the matrix for fixing the shape with the same elements
tensorA = torch.tensor([[1,2,3],
                        [4,5,6]])
tensorA.mT

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [118]:
# find the positional min and max, i.e., index of min and max
x = torch.rand(3, 2)
x

tensor([[0.6238, 0.3110],
        [0.3220, 0.6960],
        [0.5161, 0.6148]])

In [119]:
x.argmax()

tensor(3)

In [122]:
x.argmin()

tensor(1)

In [126]:
## reshaping, stacking, squeezing and unsqueezing tensors

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [130]:
# add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [132]:
# change the view
z = x.view(1, 9) # changing z will change x bcz the view of a tensor shares the same memory as the original tensor
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [137]:
# stack tesnors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [138]:
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [150]:
x_reshaped.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [165]:
y = torch.arange(1, 10).reshape(1, 3, 3)
y, y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [167]:
y_permuted = y.permute(1, 0, 2)
y_permuted, y_permuted.shape

(tensor([[[1, 2, 3]],
 
         [[4, 5, 6]],
 
         [[7, 8, 9]]]),
 torch.Size([3, 1, 3]))

In [178]:
y[0, 1, :]

tensor([4, 5, 6])

In [179]:
torch.cuda.is_available()

False